### ISSUE TITLE
Error receiving prediction result, please try refresh the page

### ISSUE THREAD

**Issue by ZF4444** [datamllab/rlcard-showdown#14]
本地进入斗地主网页后，该模型做动作时，提示“Error receiving prediction result, please try refresh the page”

**Comment by ZF4444** [comment]
> @ZF4444 后台服务器是不是没开

前端后端都开了

**Comment by ZF4444** [comment]
> @ZF4444 后台服务器是不是没开

 Node.js and NPM版本有要求吗？我的是14.16.0 和6.14.11

**Comment by daochenzha** [comment]
@hsywhu

**Comment by hsywhu** [comment]
前端能起来的话就跟node.js和npm版本没关系，后端服务有两个，一个是为leaderboard服务的，运行在8000端口，一个是为斗地主服务的，运行在5000端口。斗地主模型做动作是依赖于5000端口上的服务的，看看是不是后端启动错了。
