### ISSUE TITLE
无法在 macOS M1 芯片(ARM)环境下安装

### ISSUE THREAD

**Issue by SpaceX-Vision** [datamllab/rlcard-showdown#17]
Could not find a version that satisfies the requirement onnxruntime (from -r requirements.txt (line 8)) (from versions: )
No matching distribution found for onnxruntime (from -r requirements.txt (line 8))

**Comment by daochenzha** [comment]
@SpaceX-Vision onnxruntime只是加速用的。可以用torch推理，比如在https://github.com/datamllab/rlcard-showdown/blob/master/pve_server/run_douzero.py#L24 设为`use_onnx=True`
