### ISSUE TITLE
前端项目安装报错

### ISSUE THREAD

**Issue by jidebingfeng** [datamllab/rlcard-showdown#19]
我用最新的稳定版nodejs（v16.13.0），安装报错。mac和windows都试过不行。
![image](https://user-images.githubusercontent.com/1570487/141779080-1631965a-28b4-42bc-b1d9-3ca77358eac4.png)
加了`--legacy-peer-deps`参数后提示需要python2.7
指定了`--python`后还有其他错误

**Comment by hsywhu** [comment]
试了一下高版本node(v14, v16)确实有报错问题，可以尝试用[nvm](https://github.com/nvm-sh/nvm)切换到node 10再安装
