### ISSUE TITLE
请问RLcard能否让玩家与两个训练过的AI一起玩

### ISSUE THREAD

**Issue by sssun826804236** [datamllab/rlcard-showdown#33]
刚刚安装好RLcard，运行启动后端和前端之后，发现只能在里边设置评估次数以及上传模型，想请问一下这版rlcard有没有Demo演示里那种玩家与AI对战的功能

**Comment by hsywhu** [comment]
斗地主对战可以进入http://127.0.0.1:3000/pve/doudizhu-demo
需要pve_server启动在http://127.0.0.1:5000/

**Comment by sssun826804236** [comment]
> 

不可以设置电脑的AI吗

**Comment by sssun826804236** [comment]
> 斗地主对战可以进入 http://127.0.0.1:3000/pve/doudizhu-demo 需要pve_server启动在 http://127.0.0.1:5000/

请问可以自己设置电脑ai吗，

**Comment by sssun826804236** [comment]
> 

感谢解答，
