### ISSUE TITLE
三张底牌为啥只传两张，有什么讲究吗

### ISSUE THREAD

**Issue by elonmusker** [datamllab/rlcard-showdown#43]
![image](https://github.com/datamllab/rlcard-showdown/assets/70467647/df891010-9811-4c37-91e0-f507d26bb027)
三张底牌为啥只传两张，有什么讲究吗，还是说写错了，希望能得到解决，感谢。

**Comment by hsywhu** [comment]
只会传还没出过的地主牌哈

**Comment by hsywhu** [comment]
参考 https://github.com/datamllab/rlcard-showdown/blob/dd1cfdf522d5ce2fb9ed809f804fdbdbeab020fe/src/view/PvEView/PvEDoudizhuDemoView.js#L114
