### ISSUE TITLE
gpy error occurred after npm install --force --legacy-peer-deps

### ISSUE THREAD

**Issue by Aaronscabin** [datamllab/rlcard-showdown#50]
gyp error message:

> File "/home/.node-gyp/20.9.0/include/node/common.gypi", line 1
> npm ERR!     nerate ',
> npm ERR!             ^
> npm ERR! SyntaxError: EOL while scanning string literal
> npm ERR! gyp ERR! configure error 
> npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
> npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/home/RLCard/rlcard-showdown/node_modules/node-gyp/lib/configure.js:345:16)
> npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:514:28)
> npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:294:12)
> npm ERR! gyp ERR! System Linux 5.19.0-47-generic
> npm ERR! gyp ERR! command "/usr/local/lib/nodejs/node-v20.9.0-linux-x64/bin/node" "/home/RLCard/rlcard-showdown/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
> npm ERR! gyp ERR! cwd /home/RLCard/rlcard-showdown/node_modules/node-sass
> npm ERR! gyp ERR! node -v v20.9.0
> npm ERR! gyp ERR! node-gyp -v v3.8.0
> npm ERR! gyp ERR! not ok 
> npm ERR! Build failed with error code: 1
> 
> npm ERR! A complete log of this run can be found in: /home/.npm/_logs/2023-11-20T03_48_32_851Z-debug-0.log

**Comment by hsywhu** [comment]
Please try with node v10

**Comment by Aaronscabin** [comment]
> Please try with node v10


working with node v10.24.1 on Ubuntu23.10, Thanks!!!
