### ISSUE TITLE
Django administration Password??

### ISSUE THREAD

**Issue by monkeycc** [datamllab/rlcard-showdown#6]
http://127.0.0.1:8000/admin

Django administration
Username:
Password:

python manage.py makemigrations

  File "manage.py", line 16
    ) from exc
         ^

后台登陆，应该要怎么设置

**Comment by daochenzha** [comment]
@monkeycc You may create the admin user following this guide

https://docs.djangoproject.com/en/1.8/intro/tutorial02/
