### ISSUE TITLE
在Rlcard showdown 中无法Upload model

### ISSUE THREAD

**Issue by 274927760** [datamllab/rlcard-showdown#7]
您好！请问一下该如何添加其他的模型上去呢，我添加给的样例zip文件，却提示Only zip file can be  uploaded

![image](https://user-images.githubusercontent.com/78257579/106373674-dee9e400-63b6-11eb-9d21-ff7939f5a7bf.png)

**Comment by hsywhu** [comment]
@274927760 Hello，样例的zip文件下载下来之后应该是可以直接上传的，我这边怎么尝试都没法复现您出现的问题。

**Comment by hsywhu** [comment]
> @274927760 Hello，样例的zip文件下载下来之后应该是可以直接上传的，我这边怎么尝试都没法复现您出现的问题。

更新，换了Windows电脑测了一下，复现了问题。发现下载下来的样例文件在mac系统下是application/zip，在Windows下是application/x-zip-compressed。更新了一下代码，应该已经修复了。

**Comment by 274927760** [comment]
@hsywhu 已经可以上传了 非常感谢！
