### ISSUE TITLE
Error in getting replay data

### ISSUE THREAD

**Issue by Maxwell2017** [datamllab/rlcard-showdown#9]
After Launching Tournaments in guide.md, I Click the replay button doudizhu-rule-v1  to watch the replay with doudizhu, BUT when i click start in http://localhost:3000/replay/doudizhu, Suddenly prompt me “Error in getting replay data”, Then prompted the following error “TypeError: Cannot read property 'length' of undefined”. The replay button of Texas Hold'em will not report an error, This is very confusing to me.

**Comment by hsywhu** [comment]
Hi @Maxwell2017 , thanks for reporting the issue! It's the recently pushed code for Doudizhu PvE demo that breaks the replay functionality. I pushed a quick fix towards the issue, please pull the latest code and try again. Let me know if you face further issues.

**Comment by Maxwell2017** [comment]
Thanks for the quick reply，the problem is solved

**Comment by Maxwell2017** [comment]
@hsywhu By the way, why is there no card type and probability in the frontend interface of Doudizhu?

**Comment by hsywhu** [comment]
> @hsywhu By the way, why is there no card type and probability in the frontend interface of Doudizhu?

We have that in previous version, but we found there are bugs in the functionality. It's a bit tricky to extract probability information in backend so we disabled it for now.
